language: python

python:
  - "3.6"

services: postgresql
addons:
  postgresql: "9.6"

before_install:
  - export DJANGO_SETTINGS_MODULE=worldcupprono.settings.tests
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install -r requirements-tests.txt

before_script:
  - psql -c 'create database travis_ci;' -U postgres

script: python manage.py test

notifications:
  email:
    recipients:
      - fabien@loffredo.fr
    on_success: change
    on_failure: always
